# Generated by Django 3.0.6 on 2020-05-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('data', models.TextField(help_text='Commit data in json format')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Repository')),
            ],
            options={
                'unique_together': {('repository', 'sha')},
            },
        ),
    ]
